# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-21 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='user_type',
            field=models.CharField(choices=[('ADV', 'Advertiser'), ('HST', 'Bot host')], default='ADV', max_length=3),
        ),
    ]
