# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170125_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='Closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
