# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:52
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170130_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_image_path),
        ),
    ]
