# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170130_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bot',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BotTheme'),
        ),
    ]
