# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:56
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170207_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
