# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:51
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_myprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.get_image_path)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('WAIT', 'On moderation'), ('OK', 'OK')], default='NEW', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myprofile',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WAIT', 'On moderation'), ('OK', 'OK')], default='NEW', max_length=4),
        ),
    ]
