# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170209_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'permissions': (('Moderate', 'Moderate'),)},
        ),
    ]
