# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170209_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
