# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170213_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={},
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('WAIT', 'On moderation'), ('OK', 'OK')], default='NEW', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('WAIT', 'On moderation'), ('OK', 'OK')], default='NEW', max_length=4, null=True),
        ),
    ]
