# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170214_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
