# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170214_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Bot')),
            ],
        ),
    ]
