# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='Advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Advert'),
            preserve_default=False,
        ),
    ]
