# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_adv_advert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adv',
            old_name='Advert',
            new_name='advert',
        ),
    ]
