# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170405_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='bot_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Bot'),
        ),
    ]
