# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170410_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='bot',
        ),
        migrations.AddField(
            model_name='advert',
            name='bot',
            field=models.ManyToManyField(to='accounts.Bot'),
        ),
    ]
