# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20170412_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertBotSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='advert',
            name='bot',
        ),
        migrations.AddField(
            model_name='advertbotset',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Advert'),
        ),
        migrations.AddField(
            model_name='advertbotset',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Bot'),
        ),
    ]
