# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20170413_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='user_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
