# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('WAIT', 'On moderation'), ('OK', 'OK')], default='NEW', max_length=4, null=True),
        ),
    ]
