# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bots'),
        ),
    ]
