# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_botimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='prefered_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
