# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20170608_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='prefered_datetime',
        ),
        migrations.AddField(
            model_name='advertbotset',
            name='prefered_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
