# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_bot_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='text',
        ),
        migrations.AddField(
            model_name='payout',
            name='cardout',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='walletoutname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='walletout',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
