# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_auto_20170321_1038'),
        ('telebot', '0002_auto_20170322_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Update'),
            preserve_default=False,
        ),
    ]
